University application CRM/Models/University.cs
using System.ComponentModel.DataAnnotations;

namespace University_application_CRM.Models
{
    public class University
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int CityId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public int Founded { get; set; }
        [Required]
        [DataType(DataType.Url)]
        public string Website { get; set; }
        [Required]
        public string Sector { get; set; }
        [Required]
        public int StudentCount { get; set; }
        public string About_fa { get; set; }
        public string About_en { get; set; }
        [Required]
        public string SchoolType { get; set; }
        public bool ActiveInSearch { get; set; }
        public bool ActiveInNewApps { get; set; }

        public List<UniversityProgram> UniversityPrograms { get; set; }
        public City City { get; set; }
    }
}

University application CRM/Models/UniversityViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace University_application_CRM.Models
{
    //static options
    public enum Sector
    {
        Public = 1,
        Private = 2
    }
    public enum SchoolType
    {
        College = 1,
        High_School = 2,
        Institution = 3,
        University = 4
    }

    public class UniversityViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int CityId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public int Founded { get; set; }
        [Required]
        [DataType(DataType.Url)]
        public string Website { get; set; }
        [Required]
        public Sector Sector { get; set; }
        [Required]
        public int StudentCount { get; set; }
        public string About_fa { get; set; }
        public string About_en { get; set; }
        [Required]
        public SchoolType SchoolType { get; set; }
        [Required]
        [DataType(DataType.Upload)]
        public IFormFile UniLogo { get; set; }
        public bool ActiveInSearch { get; set; }
        public bool ActiveInNewApps { get; set; }

        public List<UniversityProgram> UniversityPrograms { get; set; }
        public IEnumerable<City> Cities { get; set; }
        public string City { get; set; }
    }
}

University application CRM/Controllers/UniversitiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class UniversitiesController : Controller
    {
        private CRMContext _context;
        public UniversitiesController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var university = _context.Universities;
            return View(university);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var cityList = _context.Cities.ToList();
            var universityVM = new UniversityViewModel() { Cities = cityList};
            return View(universityVM);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UniversityViewModel universityVM)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}
            var city = _context.Cities.Where(c => c.Name == universityVM.City).FirstOrDefault();
            var university = new University()
            {
                CityId = city.Id,
                Title = universityVM.Title,
                Address = universityVM.Address,
                Founded = universityVM.Founded,
                Sector = universityVM.Sector.ToString(),
                Website = universityVM.Website,
                StudentCount = universityVM.StudentCount,
                About_en = universityVM.About_en,
                About_fa = universityVM.About_fa,
                SchoolType = universityVM.SchoolType.ToString(),
                ActiveInSearch = universityVM.ActiveInSearch,
                ActiveInNewApps = universityVM.ActiveInNewApps
            };
            _context.Universities.Add(university);
            _context.SaveChanges();

            var path = Path.Combine(Directory.GetCurrentDirectory(), 
                "wwwroot", "Images", "UniLogos", university.Id + ".jpg");
            universityVM.UniLogo.CopyTo(new FileStream(path, FileMode.Create));

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var university = _context.Universities.Where(i => i.Id == id)
                .Include(c => c.City).FirstOrDefault();

            var cityList = _context.Cities.ToList();

            var universityVM = new UniversityViewModel()
            {
                Id = university.Id,
                Title = university.Title,
                Address = university.Address,
                Founded = university.Founded,
                Sector = Enum.Parse<Sector>(university.Sector),
                Website = university.Website,
                StudentCount = university.StudentCount,
                About_en = university.About_en,
                About_fa = university.About_fa,
                Cities = cityList,
                City = university.City.Name,
                SchoolType = Enum.Parse<SchoolType>(university.SchoolType),
                ActiveInSearch = university.ActiveInSearch,
                ActiveInNewApps = university.ActiveInNewApps
            };
            return View(universityVM);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UniversityViewModel universityVM)
        {
            var university = _context.Universities.Find(universityVM.Id);
            university.Title = universityVM.Title;
            university.Address = universityVM.Address;
            university.Founded = universityVM.Founded;
            university.Sector = universityVM.Sector.ToString();
            university.Website = universityVM.Website;
            university.StudentCount = universityVM.StudentCount;
            university.About_en = universityVM.About_en;
            university.About_fa = universityVM.About_fa;
            university.SchoolType = universityVM.SchoolType.ToString();
            university.ActiveInSearch = universityVM.ActiveInSearch;
            university.ActiveInNewApps = universityVM.ActiveInNewApps;
            _context.SaveChanges();

            var path = Path.Combine(Directory.GetCurrentDirectory(),
                "wwwroot", "Images", "UniLogos", university.Id + ".jpg");
            universityVM.UniLogo.CopyTo(new FileStream(path, FileMode.Create));

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var university = _context.Universities.Where(i => i.Id == id)
                .Include(c => c.City).FirstOrDefault();

            var cityList = _context.Cities.ToList();

            var universityVM = new UniversityViewModel()
            {
                Id = university.Id,
                Title = university.Title,
                Address = university.Address,
                Founded = university.Founded,
                Sector = Enum.Parse<Sector>(university.Sector),
                Website = university.Website,
                StudentCount = university.StudentCount,
                About_en = university.About_en,
                About_fa = university.About_fa,
                Cities = cityList,
                City = university.City.Name,
                SchoolType = Enum.Parse<SchoolType>(university.SchoolType),
                ActiveInSearch = university.ActiveInSearch,
                ActiveInNewApps = university.ActiveInNewApps
            };
            return View(universityVM);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var university = _context.Universities.Find(id);
            _context.Remove(university);
            _context.SaveChanges();

            var path = Path.Combine(Directory.GetCurrentDirectory(),
                "wwwroot", "Images", "UniLogos", university.Id + ".jpg");
            System.IO.File.Delete(path);

            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Controllers/UniversityProgramsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class UniversityProgramsController : Controller
    {
        private CRMContext _context;

        public UniversityProgramsController(CRMContext context)
        {
            _context = context;
        }

        [Route("/Universities/{id}/Index")]
        public IActionResult Index([FromRoute]int id)
        {
            var uniprograms = _context.UniversityPrograms.Where(i => i.UniversityId == id)
                .Include(i => i.Program).ThenInclude(i => i.Speciality)
                .Include(i => i.Program).ThenInclude(i => i.Language).ToList();
            ViewData["UniId"] = id;

            return View(uniprograms);
        }

        [HttpGet]
        [Route("/Universities/{id}/Create")]
        public IActionResult Create([FromRoute] int id)
        {
            var programs = _context.Programs.Include(i => i.Speciality).Include(i => i.Language).ToList();

            var UniProgramsVM = new UniversityProgramViewModel()
            {
                UniversityId = id,
                Programs = programs,
                ActiveInNewApps = true,
                ActiveInSearch = true
            };

            return View(UniProgramsVM);
        }

        [HttpPost]
        [Route("/Universities/{id}/Create")]
        public IActionResult Create(UniversityProgramViewModel UniProgramVM, [FromRoute] int id)
        {
            var Speciality = _context.Specialities.Where(i => i.Name_en == UniProgramVM.ProgramName).FirstOrDefault();
            var Program = _context.Programs.Where(n => n.SpecialityId == Speciality.Id).FirstOrDefault();

            var UniProgram = new UniversityProgram()
            {
                UniversityId = id,
                ProgramId = Program.Id,
                TuitionFee = UniProgramVM.TuitionFee,
                TuitionFeeDis = UniProgramVM.TuitionFeeDis,
                Commission = UniProgramVM.Commission,
                AdmissionReq_en = UniProgramVM.AdmissionReq_en,
                AdmissionReq_fa = UniProgramVM.AdmissionReq_fa,
                CareerPath_en = UniProgramVM.CareerPath_en,
                CareerPath_fa = UniProgramVM.CareerPath_fa,
                Description_en = UniProgramVM.Description_en,
                Description_fa = UniProgramVM.Description_fa,
                StudyYears = UniProgramVM.StudyYears,
                TuitionUnit = UniProgramVM.TuitionUnit.ToString(),
                ActiveInNewApps = UniProgramVM.ActiveInNewApps,
                ActiveInSearch = UniProgramVM.ActiveInSearch
            };

            _context.Add(UniProgram);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index), id);
        }

        [HttpGet]
        [Route("/Universities/{id}/Edit")]
        public IActionResult Edit(int id)
        {

            return View();
        }

        [HttpPost]
        [Route("/Universities/{id}/Edit")]
        public IActionResult Edit(ProgramsViewModel programsVM)
        {
            var Speciality = _context.Specialities.Where(i => i.Name_en == programsVM.Speciality).FirstOrDefault();
            var Language = _context.Languages.Where(i => i.Name == programsVM.Language).FirstOrDefault();
            var Program = _context.Programs.Find(programsVM.Id);

            Program.SpecialityId = Speciality.Id;
            Program.LanguageId = Language.Id;
            Program.Level = programsVM.Level.ToString();
            Program.ActiveInSearch = programsVM.ActiveInSearch;
            Program.ActiveInNewApps = programsVM.ActiveInNewApps;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/Universities/{id}/Delete")]
        public IActionResult Delete(int id)
        {
            var Program = _context.Programs.Find(id);

            return View(Program);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Route("/Universities/{id}/Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var Program = _context.Programs.Find(id);
            _context.Programs.Remove(Program);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Views/Universities/Create.cshtml
@model UniversityViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Add new Speciality</h1>

<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input class="form-control" asp-for="Title">
    </div>
    <div class="mb-3">
        <label asp-for="Address" class="form-label"></label>
        <input class="form-control" asp-for="Address">
    </div>
    <div class="mb-3">
        <label asp-for="Founded" class="form-label"></label>
        <input class="form-control" asp-for="Founded">
    </div>
    <div class="mb-3">
        <label asp-for="Sector" class="form-label"></label>
        <select class="form-control" asp-for="Sector" asp-items="Html.GetEnumSelectList<Sector>()">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Website" class="form-label"></label>
        <input class="form-control" asp-for="Website">
    </div>
    <div class="mb-3">
        <label asp-for="StudentCount" class="form-label"></label>
        <input class="form-control" asp-for="StudentCount">
    </div>
    <div class="mb-3">
        <label asp-for="About_en" class="form-label"></label>
        <textarea class="form-control" asp-for="About_en"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="About_fa" class="form-label"></label>
        <textarea class="form-control" asp-for="About_fa"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="SchoolType" class="form-label"></label>
        <select class="form-control" asp-for="SchoolType" asp-items="Html.GetEnumSelectList<SchoolType>()">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Cities" class="form-label">City</label>
        <select class="form-control" asp-for="City" asp-items="@(new SelectList(Model.Cities, "Name", "Name"))">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="UniLogo" class="form-label"></label>
        <input class="form-control" asp-for="UniLogo">
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInSearch">
        <label class="form-check-label" asp-for="ActiveInSearch"></label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInNewApps">
        <label class="form-check-label" asp-for="ActiveInNewApps"></label>
    </div>

    <button type="submit" class="btn btn-success" asp-controller="Universities" asp-action="Create">Add</button>
</form>

University application CRM/Views/Universities/Delete.cshtml
@model UniversityViewModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Are You Sure You want To Delete This University?</h1>

<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input class="form-control" asp-for="Title" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="Address" class="form-label"></label>
        <input class="form-control" asp-for="Address" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="Founded" class="form-label"></label>
        <input class="form-control" asp-for="Founded" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="Sector" class="form-label"></label>
        <select class="form-control" asp-for="Sector" asp-items="Html.GetEnumSelectList<Sector>()" disabled>
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Website" class="form-label"></label>
        <input class="form-control" asp-for="Website" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="StudentCount" class="form-label"></label>
        <input class="form-control" asp-for="StudentCount" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="About_en" class="form-label"></label>
        <textarea class="form-control" asp-for="About_en" disabled></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="About_fa" class="form-label"></label>
        <textarea class="form-control" asp-for="About_fa" disabled></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="SchoolType" class="form-label"></label>
        <select class="form-control" asp-for="SchoolType" asp-items="Html.GetEnumSelectList<SchoolType>()" disabled>
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Cities" class="form-label">City</label>
        <select class="form-control" asp-for="City" asp-items="@(new SelectList(Model.Cities, "Name", "Name"))" disabled>
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="UniLogo" class="form-label"></label>
        <input class="form-control" asp-for="UniLogo" disabled>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInSearch" disabled>
        <label class="form-check-label" asp-for="ActiveInSearch" ></label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInNewApps" disabled>
        <label class="form-check-label" asp-for="ActiveInNewApps"></label>
    </div>
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger" asp-controller="Universities" asp-action="Delete" 
        asp-route-id="@Model.Id">Yes</button>
    <button class="btn btn-success" asp-controller="Universities" asp-action="Index">No</button>
</form>

University application CRM/Views/Universities/Edit.cshtml
@model UniversityViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input class="form-control" asp-for="Title">
    </div>
    <div class="mb-3">
        <label asp-for="Address" class="form-label"></label>
        <input class="form-control" asp-for="Address">
    </div>
    <div class="mb-3">
        <label asp-for="Founded" class="form-label"></label>
        <input class="form-control" asp-for="Founded">
    </div>
    <div class="mb-3">
        <label asp-for="Sector" class="form-label"></label>
        <select class="form-control" asp-for="Sector" asp-items="Html.GetEnumSelectList<Sector>()">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Website" class="form-label"></label>
        <input class="form-control" asp-for="Website">
    </div>
    <div class="mb-3">
        <label asp-for="StudentCount" class="form-label"></label>
        <input class="form-control" asp-for="StudentCount">
    </div>
    <div class="mb-3">
        <label asp-for="About_en" class="form-label"></label>
        <textarea class="form-control" asp-for="About_en"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="About_fa" class="form-label"></label>
        <textarea class="form-control" asp-for="About_fa"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="SchoolType" class="form-label"></label>
        <select class="form-control" asp-for="SchoolType" asp-items="Html.GetEnumSelectList<SchoolType>()">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Cities" class="form-label">City</label>
        <select class="form-control" asp-for="City" asp-items="@(new SelectList(Model.Cities, "Name", "Name"))">
            <option selected="selected" value="">Please Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="UniLogo" class="form-label"></label>
        <input class="form-control" asp-for="UniLogo">
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInSearch">
        <label class="form-check-label" asp-for="ActiveInSearch"></label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" asp-for="ActiveInNewApps">
        <label class="form-check-label" asp-for="ActiveInNewApps"></label>
    </div>
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-success" asp-controller="Universities" asp-action="Edit">Edit</button>
</form>

University application CRM/Views/Universities/Index.cshtml
@model IEnumerable<University>
@{
    ViewData["Title"] = "Index";
}

<h1>Universities</h1>

<a class="btn btn-success" asp-controller="Universities" asp-action="Create">Add University</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col"> </th>
            <th scope="col"> </th>
        </tr>
    </thead>
    <tbody>

        @{var i = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th> @{i += 1;}
                <td>
                    <img src="/Images/UniLogos/@(item.Id).jpg" style="width: 50px; height: 50px;">
                </td>
                <td>@item.Title</td>
                <td>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a> 
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td><a class="btn btn-info" asp-controller="UniversityPrograms" asp-action="index" asp-route-id="@item.Id">Programs</a></td>
            </tr>
        }

    </tbody>
</table>