University application CRM/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class CountriesController : Controller
    {
        private CRMContext _context;
        public CountriesController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var countries = _context.Countries;
            return View(countries);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var country = new Country();
            return View(country);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Country country)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var Country = new Country()
            {
                Name = country.Name,
                Cities = null
            };
            _context.Countries.Add(Country);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var country = _context.Countries.Where(i => i.Id == id).FirstOrDefault();
            return View(country);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Country country)
        {
            var Country = _context.Countries.Where(i => i.Id == country.Id).FirstOrDefault();
            Country.Name = country.Name;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var country = _context.Countries.Where(i => i.Id == id).FirstOrDefault();
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var country = _context.Countries.Find(id);
            _context.Remove(country);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
    }
}

University application CRM/Controllers/LanguagesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class LanguagesController : Controller
    {
        private CRMContext _context;
        public LanguagesController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var languages = _context.Languages;
            return View(languages);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var country = new Language();
            return View(country);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Language language)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var Language = new Language()
            {
                Name = language.Name,
            };
            _context.Languages.Add(Language);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var language = _context.Languages.Where(i => i.Id == id).FirstOrDefault();
            return View(language);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Language language)
        {
            var Language = _context.Languages.Where(i => i.Id == language.Id).FirstOrDefault();
            Language.Name = language.Name;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var language = _context.Languages.Where(i => i.Id == id).FirstOrDefault();
            if (language == null)
            {
                return NotFound();
            }
            return View(language);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var language = _context.Languages.Find(id);
            _context.Remove(language);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Controllers/ProgramsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class ProgramsController : Controller
    {
        private CRMContext _context;

        public ProgramsController(CRMContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            var programs = _context.Programs.Include(i => i.Speciality).Include(i => i.Language);
            return View(programs);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var specialities = _context.Specialities.ToList();
            var languages = _context.Languages.ToList();

            var programsVM = new ProgramsViewModel()
            {
                Specialities = specialities,
                Languages = languages,
                ActiveInNewApps = true,
                ActiveInSearch = true
            };

            return View(programsVM);
        }

        [HttpPost]
        public IActionResult Create(ProgramsViewModel programsVM)
        {
            var Speciality = _context.Specialities.Where(i => i.Name_en == programsVM.Speciality).FirstOrDefault();
            var Language = _context.Languages.Where(i => i.Name == programsVM.Language).FirstOrDefault();

            var Program = new Programs()
            {
                SpecialityId = Speciality.Id,
                LanguageId = Language.Id,
                Level = programsVM.Level.ToString(),
                ActiveInSearch = programsVM.ActiveInSearch,
                ActiveInNewApps = programsVM.ActiveInNewApps
            };
            _context.Add(Program);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var Program = _context.Programs.Where(i => i.Id == id)
                .Include(i => i.Speciality).Include(i => i.Language).FirstOrDefault();

            var specialities = _context.Specialities.ToList();
            var languages = _context.Languages.ToList();

            var programsVM = new ProgramsViewModel()
            {
                Specialities = specialities,
                Speciality = Program.Speciality.Name_en,
                Languages = languages,
                Language = Program.Language.Name,
                Level = Enum.Parse<Level>(Program.Level),
                ActiveInSearch = Program.ActiveInSearch,
                ActiveInNewApps = Program.ActiveInNewApps
            };

            return View(programsVM);
        }

        [HttpPost]
        public IActionResult Edit(ProgramsViewModel programsVM)
        {
            var Speciality = _context.Specialities.Where(i => i.Name_en == programsVM.Speciality).FirstOrDefault();
            var Language = _context.Languages.Where(i => i.Name == programsVM.Language).FirstOrDefault();
            var Program = _context.Programs.Find(programsVM.Id);
            
            Program.SpecialityId = Speciality.Id;
            Program.LanguageId = Language.Id;
            Program.Level = programsVM.Level.ToString();
            Program.ActiveInSearch = programsVM.ActiveInSearch;
            Program.ActiveInNewApps = programsVM.ActiveInNewApps;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var Program = _context.Programs.Find(id);

            return View(Program);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var Program = _context.Programs.Find(id);
            _context.Programs.Remove(Program);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Controllers/StudyFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class StudyFieldsController : Controller
    {
        private CRMContext _context;
        public StudyFieldsController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var studyField = _context.StudyFields;
            return View(studyField);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var studyField = new StudyField();
            return View(studyField);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudyField studyField)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var StudyField = new StudyField()
            {
                Name_en = studyField.Name_en,
                Name_fa = studyField.Name_fa
            };
            _context.StudyFields.Add(StudyField);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var studyField = _context.StudyFields.Where(i => i.Id == id).FirstOrDefault();
            return View(studyField);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudyField studyField)
        {
            var StudyField = _context.StudyFields.Where(i => i.Id == studyField.Id).FirstOrDefault();

            StudyField.Name_en = studyField.Name_en;
            StudyField.Name_fa = studyField.Name_fa;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var studyField = _context.StudyFields.Where(i => i.Id == id).FirstOrDefault();
            if (studyField == null)
            {
                return NotFound();
            }
            return View(studyField);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var studyField = _context.StudyFields.Find(id);
            _context.Remove(studyField);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University_application_CRM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/University_application_CRM.styles.css" asp-append-version="true" />
</head>

<body>

<div class="container-fluid">
    <div class="row flex-nowrap">
        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline" style="text-align:center;">University Application CRM</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Languages" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Languages</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="StudyFields" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Study Fields</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Universities" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Universities</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Countries" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Countries</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Programs" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Programs</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Programs" asp-action="Search">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Programs Search</span>
                            </a>
                        </li>
                        <hr>
                        <li class="nav-item">
                            <a class="nav-link align-middle px-0" asp-area="" asp-controller="Home" asp-action="Logout">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Logout</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        }
        <div class="col py-3">
            @RenderBody()
        </div>
    </div>
</div>

</body>

@RenderSection("Scripts",false)
</html>