University application CRM/Models/StudyField.cs
using System.ComponentModel.DataAnnotations;

namespace University_application_CRM.Models
{
    public class StudyField
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name_en { get; set; }
        [Required]
        public string Name_fa { get; set; }
        public List<Speciality> Specialities { get; set; }
    }
}

University application CRM/Controllers/SpecialitiesController.cs
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class SpecialitiesController : Controller
    {
        private CRMContext _context;
        public SpecialitiesController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index(int id)
        {
            var specialities = _context.Specialities.Where(s => s.StudyFieldId == id);
            return View(specialities);
        }


        // GET: CountriesController/Create
        public IActionResult Create(int id)
        {
            var speciality = new Speciality() { StudyFieldId = id};
            return View(speciality);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Speciality speciality)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var Speciality = new Speciality()
            {
                StudyFieldId = speciality.StudyFieldId,
                Name_en = speciality.Name_en,
                Name_fa = speciality.Name_fa
            };
            _context.Specialities.Add(Speciality);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index), new { id = Speciality.StudyFieldId });
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var speciality = _context.Specialities.Where(i => i.Id == id).FirstOrDefault();
            return View(speciality);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Speciality speciality)
        {
            var Speciality = _context.Specialities.Where(i => i.Id == speciality.Id).FirstOrDefault();

            Speciality.Name_en = speciality.Name_en;
            Speciality.Name_fa = speciality.Name_fa;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index), new {id = speciality.StudyFieldId});
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var speciality = _context.Specialities.Where(i => i.Id == id).FirstOrDefault();
            if (speciality == null)
            {
                return NotFound();
            }
            return View(speciality);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var speciality = _context.Specialities.Find(id);
            _context.Remove(speciality);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index), new { id = speciality.StudyFieldId });
        }
    }
}

University application CRM/Controllers/StudyFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class StudyFieldsController : Controller
    {
        private CRMContext _context;
        public StudyFieldsController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var studyField = _context.StudyFields;
            return View(studyField);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var studyField = new StudyField();
            return View(studyField);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudyField studyField)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var StudyField = new StudyField()
            {
                Name_en = studyField.Name_en,
                Name_fa = studyField.Name_fa
            };
            _context.StudyFields.Add(StudyField);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var studyField = _context.StudyFields.Where(i => i.Id == id).FirstOrDefault();
            return View(studyField);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudyField studyField)
        {
            var StudyField = _context.StudyFields.Where(i => i.Id == studyField.Id).FirstOrDefault();

            StudyField.Name_en = studyField.Name_en;
            StudyField.Name_fa = studyField.Name_fa;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var studyField = _context.StudyFields.Where(i => i.Id == id).FirstOrDefault();
            if (studyField == null)
            {
                return NotFound();
            }
            return View(studyField);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var studyField = _context.StudyFields.Find(id);
            _context.Remove(studyField);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

University application CRM/Views/StudyFields/Create.cshtml
@model StudyField
@{
    ViewData["Title"] = "Create";
}

<h1>Add new Study Field</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Name_en" class="form-label"></label>
        <input class="form-control" asp-for="Name_en">
    </div>
    <div class="mb-3">
        <label asp-for="Name_fa" class="form-label"></label>
        <input class="form-control" asp-for="Name_fa">
    </div>
    <button type="submit" class="btn btn-success" asp-controller="StudyFields" asp-action="Create">Add</button>
</form>

University application CRM/Views/StudyFields/Delete.cshtml
@model StudyField
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h1 class="alert-danger">Are you sure you want to delete this Language?</h1>

<form method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <button type="submit" class="btn btn-danger" asp-controller="StudyFields" asp-action="Delete">Yes</button>
    <button class="btn btn-success" asp-controller="StudyFields" asp-action="Index">No</button>
</form>

University application CRM/Views/StudyFields/Edit.cshtml
@model StudyField
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Name_en" class="form-label"></label>
        <input class="form-control" asp-for="Name_en">
    </div>
    <div class="mb-3">
        <label asp-for="Name_fa" class="form-label"></label>
        <input class="form-control" asp-for="Name_fa">
    </div>
    <input type="hidden" class="form-control" asp-for="Id">
    <button type="submit" class="btn btn-success" asp-controller="StudyFields" asp-action="Edit">Edit</button>
</form>

University application CRM/Views/StudyFields/Index.cshtml
@model IEnumerable<StudyField>
@{
    ViewData["Title"] = "Index";
}

<h1>Study Fields</h1>

<a class="btn btn-success" asp-controller="StudyFields" asp-action="Create">Add Study Field</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col"> </th>
            <th scope="col"> </th>
            <th scope="col"> </th>
        </tr>
    </thead>
    <tbody>

        @{var i = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th> @{i += 1;}
                <td>@item.Name_en | @item.Name_fa</td>
                <td>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a> 
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    <a class="btn btn-warning" asp-controller="Specialities" asp-action="index" asp-route-id="@item.Id">Specialities</a>
                    <a class="btn btn-success" asp-controller="Specialities" asp-action="create" asp-route-id="@item.Id">Add Speciality</a>
                </td>
            </tr>
        }

    </tbody>
</table>