University application CRM/Models/Country.cs
using System.ComponentModel.DataAnnotations;

namespace University_application_CRM.Models
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public List<City> Cities { get; set; }
    }
}

University application CRM/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class CitiesController : Controller
    {
        private CRMContext _context;
        public CitiesController(CRMContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            var cities = _context.Cities.Where(i => i.CountryId == id);
            return View(cities);
        }

        // GET: CitiesController/Create
        public IActionResult Add(int countryid)
        {
            var city = new City() { CountryId = countryid };
            return View(city);
        }

        // POST: CitiesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(City city)
        {
            var City = new City()
            {
                CountryId = city.CountryId,
                Name = city.Name
            };
            _context.Add(City);
            _context.SaveChanges();
            return RedirectToAction("Index", new { id = city.CountryId });
        }

        // GET: CitiesController/Edit/5
        public IActionResult Edit(int id)
        {
            var city = _context.Cities.Where(i => i.Id == id).FirstOrDefault();
            return View(city);
        }

        // POST: CitiesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(City city)
        {
            var City = _context.Cities.Where(i => i.Id == city.Id).FirstOrDefault();
            City.Name = city.Name;
            _context.SaveChanges();
            return RedirectToAction("Index", new { id = city.CountryId });
        }

        // GET: CitiesController/Delete/5
        public IActionResult Delete(int id)
        {
            var city = _context.Cities.Where(i => i.Id == id).FirstOrDefault();
            return View(city);
        }

        // POST: CitiesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var city = _context.Cities.Where(i => i.Id == id).FirstOrDefault();
            _context.Cities.Remove(city);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

University application CRM/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using University_application_CRM.Data;
using University_application_CRM.Models;

namespace University_application_CRM.Controllers
{
    public class CountriesController : Controller
    {
        private CRMContext _context;
        public CountriesController(CRMContext context)
        {
            _context = context;
        }


        // GET: CountriesController
        public IActionResult Index()
        {
            var countries = _context.Countries;
            return View(countries);
        }


        // GET: CountriesController/Create
        public IActionResult Create()
        {
            var country = new Country();
            return View(country);
        }

        // POST: CountriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Country country)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(country);
            //}

            var Country = new Country()
            {
                Name = country.Name,
                Cities = null
            };
            _context.Countries.Add(Country);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Edit/5
        public IActionResult Edit(int id)
        {
            var country = _context.Countries.Where(i => i.Id == id).FirstOrDefault();
            return View(country);
        }

        // POST: CountriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Country country)
        {
            var Country = _context.Countries.Where(i => i.Id == country.Id).FirstOrDefault();
            Country.Name = country.Name;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CountriesController/Delete/5
        public IActionResult Delete(int id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var country = _context.Countries.Where(i => i.Id == id).FirstOrDefault();
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: CountriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var country = _context.Countries.Find(id);
            _context.Remove(country);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
    }
}

University application CRM/Views/Countries/Create.cshtml
@model Country
@{
    ViewData["Title"] = "Create";
}

<h1>Add new Country</h1>

<form method="post">
  <div class="mb-3">
    <label asp-for="Name" class="form-label"></label>
    <input class="form-control" asp-for="Name">
  </div>
  <button type="submit" class="btn btn-success" asp-controller="Countries" asp-action="Create">Add</button>
</form>

University application CRM/Views/Countries/Delete.cshtml
@model Country
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h1 class="alert-danger">Are you sure you want to delete this country?</h1>

<form method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <button type="submit" class="btn btn-danger" asp-controller="Countries" asp-action="Delete">Yes</button>
    <button class="btn btn-success" asp-controller="Countries" asp-action="Index">No</button>
</form>

University application CRM/Views/Countries/Edit.cshtml
@model Country
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input class="form-control" asp-for="Name">
    </div>
        <input type="hidden" class="form-control" asp-for="Id">
    <button type="submit" class="btn btn-success" asp-controller="Countries" asp-action="Edit">Edit</button>
</form>

University application CRM/Views/Countries/Index.cshtml
@model IEnumerable<Country>
@{
    ViewData["Title"] = "Index";
}

<h1>Countries</h1>

<a class="btn btn-success" asp-controller="Countries" asp-action="Create">Add Country</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col"> </th>
            <th scope="col"> </th>
        </tr>
    </thead>
    <tbody>

        @{var i = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th> @{i += 1;}
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-info" asp-controller="Cities" asp-action="Index" asp-route-id="@item.Id">List of Cities</a> 
                    <a class="btn btn-success" asp-controller="Cities" asp-action="Add" asp-route-countryid="@item.Id">Add City</a></td>
                <td>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a> 
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }

    </tbody>
</table>